name: schedule

on:
  schedule:
    - cron: "20 0-23/12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install golang
        uses: actions/setup-go@master
        with:
          go-version: 1.15
        id: go

      - name: Run App
        run: |
          go run main.go